### PR TITLE
Fixed Podspec to include require frameworks; fixed access modifiers t…

### PR DESCRIPTION
**Pull request by hons82**
…o be available when imported as pod.

IF you want it to be available as pod in the general [Cocoapods repository](https://cocoapods.org) youd need to to
```
$ pod spec lint
$ pod lib lint
```
and if no errors are reported
```
$ pod trunk push
```

### CODE REVIEW

**Comment by DaRkD0G** [comment]
Thanks :+1:

**Comment by DaRkD0G** [comment]
@hons82 Thanks for Pods  and more :+1:

**Comment by DaRkD0G** [comment]
@hons82  Could you tell if my new version is add with cacoapod ?

**Comment by hons82** [comment]
Works!
```bash
Installing EasyGameCenter 2.0.0 (was 1.5.1)
```

**Comment by DaRkD0G** [comment]
@hons82  Cool :) thank you again for the commandes.

**Comment by hons82** [comment]
You’re welcome…
I hope I’m able to publish something soon that uses it :-)

**Comment by DaRkD0G** [comment]
;-) I'm sure you will do a super game

**Pull request merged**
